stone-co/stone-api-docs

content/faq/_index.pt.md

bandeiras, adquirentes, tempo de ted, failed vs refunded, devolução de taxa, momento consent.

content: 1ª FAQ

---

content/sdks/Elixir

Incluir SDK Elixir. Falta incluir pasta Elixir em SDK.

Contente: SDK Elixir

---

config.toml

Adiciona o forms do pipefy a docs.

Home: Forms - Quero ser parceiro

---

content/Avisos/melhorias/_index.pt.md

frormatação, mas inclusão de limite de idempotência

Content: fix melhorias

---

content/parceiros/modelos/_index.pt.md

Content:Parcerias:Modelos

---

content/Avisos/novidades/_index.pt.md

Estrutura de subiu / previsto
- Disponibilização dos dados de quem de fato efetuou o pagamento de um boleto 
- Juros, Multas, Descontos e Multipos Descontos na emissão de boletos cobrança

Content:Avisos:Novidade:Add

---

content/Avisos/melhorias/_index.pt.md

Estrutura de subiu / previsto
- Mudança do nome do objeto payer
- Notificação por e-mail e push para parceiros no formato Conta de Liquidação
- Validação de saldo na criação de TEDs e TEfs (alterarão de data)

Content:Avisos:Melhorias:Add

---

content/referencia-da-api/pix/cadastrar-uma-chave-pix/_index.pt.md
content/referencia-da-api/pix/o-que-e-o-pix/_index.pt.md
content/referencia-da-api/pix/pagar-um-pix/_index.pt.md
content/referencia-da-api/pix/receber-um-pix-via-qr-code/_index.pt.md

adicionando conteúdos sobre pix :)

content: add pix beta to documentation

---

content/pt/docs/pix/_index.md

Content.Pix

---

content/pt/docs/pix/chaves-pix/_index.md

Content.Pix.Chaves_Pix

---

content/pt/docs/pix/chaves-pix/campos/_index.md

Content.Pix.Chaves_Pix.Objeto

---

content/pt/docs/pix/chaves-pix/criar-uma-chave-pix/_index.md

Content.Pix.Chaves_Pix.Cria_uma_chave_pix

---

content/pt/docs/pix/chaves-pix/excluir-uma-chave-pix/_index.md

Content.Pix.Chaves_Pix.Excluir_uma_chave_pix

---

content/pt/docs/pix/chaves-pix/criar-uma-chave-pix/_index.md

Content.Pix.Chaves_Pix.Criar_uma_chave_pix

---

content/pt/docs/pix/chaves-pix/status

Content.Pix.Chaves_Pix.Status_2

---

content/pt/docs/pix/chaves-pix/criar-uma-chave-pix/_index.md

Content.Pix.Chaves_Pix.Criar_uma_chave_pix_3

---

content/pt/docs/pix/chaves-pix/excluir-uma-chave-pix/_index.md

Content.Pix.Chaves_Pix.Excluir_uma_chave_pix_4

---

content/pt/docs/pix/chaves-pix/reivindicar/_index.md

Content.Pix.Chaves_Pix.Reivindicar_uma_chave_pix_5

---

content/pt/docs/pix/chaves-pix/reivindicar/_index.md

Content.Pix.Chaves_Pix.Reivindicar_uma_chave_pix_7

---

content/pt/docs/pix/chaves-pix/detalhar-uma- chave-pix/_index.md

Content.Pix.Chaves_Pix.Detalhar_uma_chave_pix_5

---

content/pt/docs/pix/chaves-pix/aprovar-ou-rejeitar-reivindicação/_index.md

inclusão webhook atualização de status

Content.Pix.Chaves_Pix.Aprovar/Rejeitar_8

---

content/pt/docs/pix/chaves-pix/listar-chaves-pix/_index.md

Content.Pix.Chaves_Pix.Listar_chaves_pix_6

---

content/pt/docs/pix/chaves-pix/detalhar-uma-reivindicação/_index.md

Content.Pix.Chaves_Pix.Detalhar_reivindicação_9

---

content/pt/docs/pix/_index.md
content/pt/docs/stone-openbank/_index.md
content/pt/docs/stone-openbank/autenticacao/_index.md
content/pt/docs/stone-openbank/codigos-de-resposta/_index.md
content/pt/docs/stone-openbank/data-e-hora/_index.md
content/pt/docs/stone-openbank/mensagens-de-erro/_index.md
content/pt/docs/stone-openbank/overview/_index.md
content/pt/docs/stone-openbank/paginacao/_index.md
content/pt/docs/stone-openbank/valores-financeiros/_index.pt.md
old_content/content/referencia-da-api/stone-openbank/_index.pt.md

o conteúdo antigo foi readequado para que os artigos ficassem compatíveis com o tema atual docsy :nerd_face:

content: add stone openbank content

---

content/pt/docs/pix/chaves-pix/reivindicar-uma-chave-pix/_index.md

alterar URL para conter account id + tirar account id do body + draft: false

Content.Pix.Chaves_Pix.Reivindicar_7

---

content/pt/docs/pix/chaves-pix/listar-reivindicacoes/_index.md

inclusão = já tem account id editado + draft + peso

Content.Pix.Chaves_Pix.Listar_reivindicações_10

---

content/pt/docs/stone-openbank/autenticacao/_index.md

Autenticação

---

content/pt/docs/agendamento/calendario-de-agendamento/_index.md
content/pt/docs/agendamento/operacoes-agendadas/_index.md

Adiciona 'Agendamento' à documentação

feat: adds 'agendamento' documentation

---

content/pt/docs/instituicoes/listar-instituicoes/_index.md
content/pt/docs/instituicoes/overview-instituicao/_index.md
content/pt/docs/instituicoes/retornar-uma-instituicao/_index.md

Adiciona 'Instituições' à documentação

feat: adds 'instituicoes' documentation

---

content/pt/_index.html

Adiciona um link para parte de guias da API e um menu com os guias.

chore: updates home page adding 'guias' link and menu

---

.gitmodules
content/pt/_index.html
package-lock.json

change submodule reference to our [docsy fork](https://github.com/stone-co/docsy). Also fix some layout misbehaviours

feat: add stone docsy theme

---

config.toml
i18n/pt.toml

Enables documentation search with [Lunr](https://www.docsy.dev/docs/adding-content/navigation/#configure-local-search-with-lunr)

feat: enable search

---

content/pt/_index.html
content/pt/docs/guias/conta-stone-sdk/overview/_index.md
content/pt/docs/referencia-da-api/stone-openbank/_index.md

alterei o link da SDK, consertei a imagem do overview da SDK e alterei o link de parcerias na home que tava errado tbm!

Link sdk home

---

content/pt/_index.html
content/pt/docs/guias/integracao/webhooks/_index.md
content/pt/docs/referencia-da-api/pix/_index.md
content/pt/docs/referencia-da-api/pix/buscar-dados-qrcode/_index.md
content/pt/docs/referencia-da-api/pix/confirmar-pagamento-pendente/_index.md
content/pt/docs/referencia-da-api/pix/criar-pagamento-pendente/_index.md

Documentação de Pix atualizada de acordo com a to-do: https://3.basecamp.com/4129278/buckets/15989146/todos/3610138188#__recording_3685805955
Aproveitei também pra mudar a ordem dos botões da home.

update pix and add pixs webhooks

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release.yml
.github/workflows/sandbox.yml
config.toml
package.json

Deploys:
- master branch: publish at http://docs.openbank.stone.com.br/sandbox/ or https://stone-co.github.io/sandbox
- TAG version: publish at http://docs.openbank.stone.com.br/ or https://stone-co.github.io/

feat: setup sandbox deploy

---

.github/workflows/release.yml

fix env var to deploy prod

---

.github/workflows/sandbox.yml
config.sdb.toml

split configs by env in a way to ensure its difference and avoid possibles conflicts on resources as internationalization(i18n)

chore: split configs by envs

---

content/pt/docs/guias/integracao-para-fornecedores/Sign-in-user/_index.md

Adicionado novo endpoint de sign-in de usuario no panda, para integração interna

feat:sign-in for panda

---

.github/CODEOWNERS
.github/workflows/release.yml
.github/workflows/sandbox.yml

Downgrade Hugo version for feature compatibility

chore: downgrade hugo build version

---

content/pt/docs/guias/integracao-para-fornecedores/Sign-in-user/_index.md

set pandas sign-in content as a draft since it's not needed in production yet

refact: set pandas sign-in content as draft

---

content/pt/docs/guias/integracao-para-fornecedores/Notification/_index.md
content/pt/docs/guias/integracao-para-fornecedores/Sign-in-user/_index.md

Add tag (Draft) for endpoints in Panda that must be in draft
Fix some terms in signin documentation that were about other endpoint

fix: update draft tag and some fixes

---

content/pt/docs/referencia-da-api/pix/_index.md
content/pt/docs/referencia-da-api/pix/buscar-dados-qrcode/_index.md

Include URL for BACEN's API Pix

feat:pix/bacen

---

content/pt/_index.html

currently, home page links in sandbox are linking to production URLs. This PR aims to fix it.

fix: change home links to relative form

---

content/pt/docs/guias/WEBHOOKS/_index.md

Changed links that were relative from home to a relative by current location form at webhooks page

fix: change links to relative form at webhooks page

---

content/pt/docs/referencia-da-api/padroes-da-api/valores-percentuais/_index.pt.md

feat: Add page about percentage pattern

---

content/pt/docs/referencia-da-api/contatos/_index.md
content/pt/docs/referencia-da-api/contatos/adicionar-conta-bancaria-a-um-contato/_index.md
content/pt/docs/referencia-da-api/contatos/atualizar-conta-bancaria-de-um-contato/_index.md
content/pt/docs/referencia-da-api/contatos/listar-contatos/_index.md
content/pt/docs/referencia-da-api/contatos/retornar-um-contato/_index.md

Add the new fields of the contacts API:
* pix_key
* account_type

feat: add pix_key and account_type fields to contacts

---

content/pt/docs/guias/CONTA-DE-PAGAMENTO/_index.md

Erro de tipografia e adicionada identidade de `organization` em conta de pagamento.
Faz sentido esse PR pessoal?

chore: add organization_id

---

content/pt/docs/referencia-da-api/simulacoes-dry-run/objetos-simulacao-de-pagamento/_index.md
content/pt/docs/referencia-da-api/simulacoes-dry-run/simular-o-pagamento-de-um-documento/_index.md

Adicionado os campos para realização de um pagamento parcial na parte de dry-run de Pagamentos.

feat:partial-payment

---

content/pt/docs/referencia-da-api/pix/recebimento/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/consultar-pix-por-e2eid/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/criar-cobranca-com-vencimento/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/listar-cobranca-com-validade/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/listar-recebimentos/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/old_cancelar-cobranca/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/old_consultar-qrcode-gerado/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/old_especificacao-do-qrcode/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/old_gerar-cobranca/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/old_listar-cobrancas/_index.md

refactor: show (draft:false) Pix receiving part and some styling tweaks

refactor:pix/recebimento:show

---

content/pt/docs/guias/APROVACAO/_index.md
content/pt/docs/guias/CONSENTIMENTO/_index.md
content/pt/docs/guias/CONTA-DE-PAGAMENTO/_index.md
content/pt/docs/guias/SDK/_index.md
content/pt/docs/guias/STONE-OPEN-BANKING/_index.md
content/pt/docs/guias/TOKEN-DE-ACESSO/_index.md
content/pt/docs/guias/WEBHOOKS/_index.md

> This PR is a proofreading of the docs Guides section. As the docs are very well-written, very few edits were needed, which mostly covered:
> - Grammar and punctuation issues
> - Spelling and concord errors
> - Capitalization inconsistencies
> - If any of the changes is not applicable, let me know and I'll revert it. :)
by @edmundobiglia

chore: Guides proofreading

---

content/pt/docs/guias/TOKEN-DE-ACESSO/_index.md

refactor/feat: adicionado novo claim "iss" para geração de token local para conseguir o access token para realizar as chamadas autenticadas em nossa API.

feat: add new claim to get access token

---

content/pt/_index.html

fix: link for sdk was wrong in home.

fix:link-sdk-home

---

content/pt/docs/guias/STONE-OPEN-BANKING/_index.md

chore: add source citation on definition of what is Openbanking / Open Finance

chore: add citation source for open banking definition

---

content/pt/docs/referencia-da-api/emissao-de-boletos/emitir-boleto/_index.md

add in emitir-boleto page information about discounts field, that are accepted at proposal and bill of exchange types

fix: add proposal type in discounts field

---

content/pt/docs/guias/WEBHOOKS/_index.md
content/pt/docs/guias/WEBHOOKS/inbound_barcode_payment_refunded.json

feat: new webhook is sent when a payment for a inbound barcode is refunded.

feat: new webhook for refund payment of a barcode

---

content/pt/docs/guias/SDK/_index.md

Atualização da documentação da Conta Stone SDK para Android.

chore: update Android SDK docs

---

content/pt/docs/referencia-da-api/pix/pagamento/_index.md

I've added `/pagamento` to some links that are currently broken.

fix: fix pix payments links

---

content/pt/docs/referencia-da-api/pix/chaves-pix/criar-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/atualizar-qrcode-estatico/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/consultar-pix-por-e2eid/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/criar-qrcode-dinamico-com-vencimento/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/criar-qrcode-dinamico/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/criar-qrcode-estatico/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/listar-cobranca-com-validade/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/listar-recebimentos/_index.md

add: new qrcode dinamic section, without fines, interest and due date
update: ordering for pix receive menu
refactor: new body request for payment invoice with due date

feat:qrcode-dinamico and chore:ordering for pix receive menu

---

content/pt/docs/referencia-da-api/pagamentos/criar-um-pagamento/_index.md

add: field amount to pay partial payments with the correct amount.

refactor: include amount in new payment

---

content/pt/docs/referencia-da-api/emissao-de-boletos/regras-de-negocio/_index.md

refactor: change payment text due on a non-business day

refactor: explain about last day to pay an invoice

---

content/pt/docs/referencia-da-api/emissao-de-boletos/emitir-boleto/_index.md

refactor: add a new text for settled invoices

refactor: new text for settled invoices

---

content/pt/docs/guias/TOKEN-DE-ACESSO/_index.md

Must be encoded in base64, not decoded!

type: replace decodificadas  to codificadas

---

content/pt/docs/referencia-da-api/emissao-de-boletos/cancelar-boleto/_index.md
content/pt/docs/referencia-da-api/emissao-de-boletos/overview-emissao-de-boletos/_index.md
content/pt/docs/referencia-da-api/emissao-de-boletos/status/_index.md

Fix `Cancelattion_request` to `CANCELLATION_REQUESTED`, removing the double `t`

fix: capitalize invoice statuses

---

content/pt/docs/guias/WEBHOOKS/_index.md
content/pt/docs/guias/WEBHOOKS/inbound_barcode_payment_validated.json

add: new webhook for invoice validated

feat: add new webhook for invoice validated

---

content/pt/docs/referencia-da-api/pix/relato-infracao/_index.md
content/pt/docs/referencia-da-api/pix/relato-infracao/listar-relatos-infracoes/_index.md

- Add infraction report introduction
- Add infraction report GET / endpoint for indirect participants

feat: add infraction reports doc

---

content/pt/docs/guias/STONE-OPEN-BANKING/_index.md
content/pt/docs/referencia-da-api/pagamentos/criar-um-pagamento/_index.md
content/pt/docs/referencia-da-api/pix/_index.md
content/pt/docs/referencia-da-api/pix/relato-infracao/_index.md

add effective payer in payments;
fix words and phrases open banking and remove "beta" in pix

feat: add effective payer in payments and fix words and phrases open banking and pix beta

---

content/pt/docs/referencia-da-api/pix/recebimento/cancelar-qrcode-dinamico-com-vencimento/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/cancelar-qrcode-dinamico/_index.md

- Add Dynamic Invoice cancellation API
- Add Dynamic Invoice With Due Date cancellation API

feat: add cancel invoice and cancel invoice with due date apis

---

content/pt/docs/referencia-da-api/pix/relato-infracao/_index.md
content/pt/docs/referencia-da-api/pix/relato-infracao/fechar-relato-infracao/_index.md

- Add close infraction report API Post

feat: add close infraction report doc

---

content/pt/docs/referencia-da-api/instituicoes/listar-instituicoes/_index.md
content/pt/docs/referencia-da-api/operacoes/_index.md
content/pt/docs/referencia-da-api/operacoes/aprovar-operacoes/_index.md
content/pt/docs/referencia-da-api/operacoes/cancelar-operacoes/_index.md
content/pt/docs/referencia-da-api/pix/_index.md
content/pt/docs/referencia-da-api/pix/chaves-pix/_index.md
content/pt/docs/referencia-da-api/pix/chaves-pix/reivindicar-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/recebimento/old_cancelar-cobranca/_index.md
old_content/content/referencia-da-api/pix/_index.pt.md
old_content/content/referencia-da-api/pix/cadastrar-uma-chave-pix/_index.pt.md
old_content/content/referencia-da-api/pix/o-que-e-o-pix/_index.pt.md
old_content/content/referencia-da-api/pix/pagar-um-pix/_index.pt.md
old_content/content/referencia-da-api/pix/receber-um-pix-via-qr-code/_index.pt.md

Fix typo on cancel and approve operations endpoint definition.

fix: typo on cancel operations endpoint

---

content/pt/docs/referencia-da-api/pix/chaves-pix/atualizar-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/chaves-pix/criar-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/chaves-pix/detalhar-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/chaves-pix/excluir-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/chaves-pix/listar-chaves-pix/_index.md

- Add entry update API
- Fix entries APIs minor errors
- Add `status` filter to entries list API

feat: add entry update api

---

content/pt/docs/referencia-da-api/emissao-de-boletos/overview-emissao-de-boletos/_index.md

After testing PR #369 in the sandbox environment, we'd found an issue of path reference for the invoice status image. Therefore, we've fixed the path aiming to solve this problem

fix: fix path reference of invoice status image

---

content/pt/docs/guias/STONE-OPEN-BANKING/_index.md

feat: change commercial form link

---

content/pt/docs/referencia-da-api/pix/devolucao/_index.md
content/pt/docs/referencia-da-api/pix/devolucao/criar-devolucao/_index.md
content/pt/docs/referencia-da-api/pix/pagamento/criar-pagamento-pendente/_index.md
content/pt/docs/referencia-da-api/pix/pagamento/detalhar-pix-enviado/_index.md

Feat:
* Add docs for Pix Refund creation
* Add idempotency error for Outbound Pix creation
Fix:
* Fix payload response for Outbound Pix creation

feat: add docs for Pix refund

---

content/pt/docs/referencia-da-api/emissao-de-boletos/overview-emissao-de-boletos/_index.md
content/pt/docs/referencia-da-api/emissao-de-boletos/status/_index.md

fix: invoice status name

---

content/pt/docs/referencia-da-api/emissao-de-boletos/emitir-boleto/_index.md
content/pt/docs/referencia-da-api/emissao-de-boletos/listar-boletos/_index.md
content/pt/docs/referencia-da-api/pagamentos/overview/_index.md

Inserido informações sobre o endereço do pagador de boleto
Inserido status de emissão de boleto: cancelled
Inserida descrição dos campos em listar boletos.

feat: add invoice payment and payment

---

.github/workflows/sandbox.yml

chore: deploy github pages to dlpco org

---

content/pt/docs/referencia-da-api/pix/apis-stone/chaves-pix/detalhar-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/apis-stone/chaves-pix/excluir-uma-chave-pix/_index.md
content/pt/docs/referencia-da-api/pix/apis-stone/pagamento/_index.md

Fix: reference link

---

content/pt/docs/referencia-da-api/emissao-de-boletos/emitir-boleto/_index.md
content/pt/docs/referencia-da-api/emissao-de-boletos/listar-boletos/_index.md
content/pt/docs/referencia-da-api/emissao-de-boletos/retornar-um-boleto/_index.md

Atualização da documentação de emissão de boleto.
https://stone-co.clickup.com/t/2t8eze6

feat: Add metadata and description to barcode payment invoice docs

---

.github/workflows/sandbox.yml

chore: remove deploy to dlpco

---

README.md
content/pt/docs/referencia-da-api/dados-da-conta/consultar-dados-do-pedido-da-conta-de-pagamento/_index.md

The Panda team make some update and receive many questions about the `https://sandbox-api.openbank.stone.com.br/api/v1/applications/:client_id/signups/:sign_up_request_id`endpoint 
With the product team aka Raissa we update this documentation adding some status descriptions and new response params

feat(payment-account): update doc and organize README.md

---

content/pt/docs/referencia-da-api/pix/apis-stone/recebimento/criar-qrcode-dinamico/_index.md

Ajustes no contrato da API de criação de QR Code dinâmico imediado. 
1. Inclusão dos campos na resposta de sucesso: 
* location
* request_for_payer
* expiration
* status
* cancelled_at
* paid_at
* additional_data
2. Inclusão das respostas de erro da API
3. Inclusão dos body params:
* additional_data
* expiration

fix: pix dynamic invoice api contract

---

content/pt/docs/referencia-da-api/pix/apis-padrao/cob/criar-cobranca-imediata/_index.md
content/pt/docs/referencia-da-api/pix/apis-padrao/cob/criar-cobranca/_index.md
content/pt/docs/referencia-da-api/pix/apis-padrao/cob/revisar-cobranca-imediata/_index.md

the fields `qr_code_content` and `qr_code_image` was added to the cob apis

feat: added qr code fields to the cob apis

---

content/pt/docs/referencia-da-api/pix/apis-stone/pagamento/consultar-pagamento/_index.md
content/pt/docs/referencia-da-api/pix/apis-stone/pagamento/criar-pagamento-pendente/_index.md

Support different errors returned by pending Pix creation API.

feat: support errors at Pix creation API

---

content/pt/docs/guias/WEBHOOKS/pix_payment_invoice.json
content/pt/docs/guias/WEBHOOKS/pix_payment_invoice_with_due_date.json
content/pt/docs/referencia-da-api/pix/apis-stone/recebimento/criar-qrcode-dinamico-com-vencimento/_index.md
content/pt/docs/referencia-da-api/pix/apis-stone/recebimento/criar-qrcode-dinamico/_index.md

add the field metada at the pix_payment invoice api

feat: add the metadata field to the pix_payment_invoices api

---

content/pt/docs/referencia-da-api/emissao-de-boletos/campos/_index.md
content/pt/docs/referencia-da-api/emissao-de-boletos/overview-emissao-de-boletos/_index.md

Add missing payment invoice fields

docs: improve invoice doc

---

content/pt/docs/guias/WEBHOOKS/pix_inbound_payment_received.json
content/pt/docs/referencia-da-api/pix/apis-stone/recebimento/consultar-pix-recido/_index.md

Add API doc for received inbound Pix

feat: add API doc for received inbound Pix
